/* =============================================================================
 * Pico Miner -- ARM Bare-Metal Driver (Zynq PS)
 *
 * Description:
 *   This program runs on the ARM Cortex-A9 processor (PS) of the Zynq SoC.
 *   It communicates with the Pico Miner HLS IP (Bitcoin double-SHA-256 miner)
 *   instantiated in the programmable logic (PL) via AXI-Lite registers.
 *
 *   The driver:
 *   1. Prepares the Bitcoin Block 170 header (real-world test vector)
 *   2. Computes the midstate on ARM (SHA-256 state after chunk 1)
 *   3. Sends midstate[8] + chunk2_tail[3] + nonce range + target to FPGA
 *   4. Starts the HW miner and polls for completion
 *   5. Reads back found_nonce + status
 *   6. Runs SW golden model for verification
 *
 * Target: Xilinx Zynq-7020 (ZedBoard)
 * Tool: Xilinx SDK 2019.1
 *
 * Note: The XPico_miner_* driver functions are AUTO-GENERATED by Vivado HLS
 *       when the IP is exported. Arrays mapped via s_axilite produce
 *       individual register accessors: Set_midstate_0 .. Set_midstate_7,
 *       Set_chunk2_tail_0 .. Set_chunk2_tail_2, etc.
 *
 * Author: Pico Miner Project
 * Date: 2026
 * =============================================================================
 */

#include <stdio.h>
#include "xparameters.h"
#include "xpico_miner.h"  /* Auto-generated by Vivado HLS export */
#include "xil_cache.h"    /* Cache init/cleanup (replaces platform.h) */

/* =============================================================================
 * SHA-256 Constants (must match pico_miner.h)
 * =============================================================================
 */
#define MIDSTATE_WORDS    8
#define CHUNK2_TAIL_WORDS 3
#define MINING_FOUND      1
#define MINING_NOT_FOUND  0

static const unsigned int SHA256_H_INIT[8] = {
    0x6a09e667u, 0xbb67ae85u, 0x3c6ef372u, 0xa54ff53au,
    0x510e527fu, 0x9b05688cu, 0x1f83d9abu, 0x5be0cd19u
};

static const unsigned int SHA256_K[64] = {
    0x428a2f98u, 0x71374491u, 0xb5c0fbcfu, 0xe9b5dba5u,
    0x3956c25bu, 0x59f111f1u, 0x923f82a4u, 0xab1c5ed5u,
    0xd807aa98u, 0x12835b01u, 0x243185beu, 0x550c7dc3u,
    0x72be5d74u, 0x80deb1feu, 0x9bdc06a7u, 0xc19bf174u,
    0xe49b69c1u, 0xefbe4786u, 0x0fc19dc6u, 0x240ca1ccu,
    0x2de92c6fu, 0x4a7484aau, 0x5cb0a9dcu, 0x76f988dau,
    0x983e5152u, 0xa831c66du, 0xb00327c8u, 0xbf597fc7u,
    0xc6e00bf3u, 0xd5a79147u, 0x06ca6351u, 0x14292967u,
    0x27b70a85u, 0x2e1b2138u, 0x4d2c6dfcu, 0x53380d13u,
    0x650a7354u, 0x766a0abbu, 0x81c2c92eu, 0x92722c85u,
    0xa2bfe8a1u, 0xa81a664bu, 0xc24b8b70u, 0xc76c51a3u,
    0xd192e819u, 0xd6990624u, 0xf40e3585u, 0x106aa070u,
    0x19a4c116u, 0x1e376c08u, 0x2748774cu, 0x34b0bcb5u,
    0x391c0cb3u, 0x4ed8aa4au, 0x5b9cca4fu, 0x682e6ff3u,
    0x748f82eeu, 0x78a5636fu, 0x84c87814u, 0x8cc70208u,
    0x90befffau, 0xa4506cebu, 0xbef9a3f7u, 0xc67178f2u
};

/* =============================================================================
 * Software SHA-256 Implementation (Golden Model for ARM verification)
 * =============================================================================
 */

static unsigned int rotr(unsigned int x, int n) {
    return (x >> n) | (x << (32 - n));
}

static unsigned int bswap32(unsigned int x) {
    return ((x & 0xFFu) << 24) | ((x & 0xFF00u) << 8) |
           ((x >> 8) & 0xFF00u) | ((x >> 24) & 0xFFu);
}

static void sha256_compress_sw(const unsigned int state_in[8],
                                const unsigned int msg[16],
                                unsigned int state_out[8])
{
    unsigned int W[64];
    unsigned int a, b, c, d, e, f, g, h;
    int i;

    for (i = 0; i < 16; i++) W[i] = msg[i];
    for (i = 16; i < 64; i++) {
        unsigned int s0 = rotr(W[i-15], 7) ^ rotr(W[i-15], 18) ^ (W[i-15] >> 3);
        unsigned int s1 = rotr(W[i-2], 17) ^ rotr(W[i-2], 19)  ^ (W[i-2] >> 10);
        W[i] = W[i-16] + s0 + W[i-7] + s1;
    }

    a = state_in[0]; b = state_in[1]; c = state_in[2]; d = state_in[3];
    e = state_in[4]; f = state_in[5]; g = state_in[6]; h = state_in[7];

    for (i = 0; i < 64; i++) {
        unsigned int S1   = rotr(e, 6) ^ rotr(e, 11) ^ rotr(e, 25);
        unsigned int ch   = (e & f) ^ ((~e) & g);
        unsigned int temp1 = h + S1 + ch + SHA256_K[i] + W[i];
        unsigned int S0   = rotr(a, 2) ^ rotr(a, 13) ^ rotr(a, 22);
        unsigned int maj  = (a & b) ^ (a & c) ^ (b & c);
        unsigned int temp2 = S0 + maj;
        h = g; g = f; f = e; e = d + temp1;
        d = c; c = b; b = a; a = temp1 + temp2;
    }

    state_out[0] = state_in[0] + a; state_out[1] = state_in[1] + b;
    state_out[2] = state_in[2] + c; state_out[3] = state_in[3] + d;
    state_out[4] = state_in[4] + e; state_out[5] = state_in[5] + f;
    state_out[6] = state_in[6] + g; state_out[7] = state_in[7] + h;
}

/* Software double-SHA-256 mining (golden model) */
static void pico_miner_sw(const unsigned int midstate[8],
                           const unsigned int chunk2_tail[3],
                           unsigned int nonce_start,
                           unsigned int nonce_end,
                           unsigned int target_hi,
                           unsigned int *found_nonce,
                           unsigned int *status)
{
    unsigned int nonce;
    int i;

    *found_nonce = 0;
    *status = MINING_NOT_FOUND;

    for (nonce = nonce_start; nonce < nonce_end; nonce++) {
        /* Build chunk 2 message block */
        unsigned int chunk2_W[16];
        chunk2_W[0]  = chunk2_tail[0];
        chunk2_W[1]  = chunk2_tail[1];
        chunk2_W[2]  = chunk2_tail[2];
        chunk2_W[3]  = nonce;
        chunk2_W[4]  = 0x80000000u;
        for (i = 5; i < 15; i++) chunk2_W[i] = 0;
        chunk2_W[15] = 0x00000280u;  /* 640 bits */

        /* First SHA-256: compress chunk 2 with midstate */
        unsigned int first_hash[8];
        sha256_compress_sw(midstate, chunk2_W, first_hash);

        /* Build second hash message block */
        unsigned int hash2_W[16];
        for (i = 0; i < 8; i++) hash2_W[i] = first_hash[i];
        hash2_W[8]  = 0x80000000u;
        for (i = 9; i < 15; i++) hash2_W[i] = 0;
        hash2_W[15] = 0x00000100u;  /* 256 bits */

        /* Second SHA-256 */
        unsigned int final_hash[8];
        sha256_compress_sw(SHA256_H_INIT, hash2_W, final_hash);

        /* Check difficulty */
        if (final_hash[0] <= target_hi) {
            *found_nonce = nonce;
            *status = MINING_FOUND;
            return;
        }
    }
}

/* =============================================================================
 * Main Program
 * =============================================================================
 */
int main(void)
{
    /* --- HLS IP instance and configuration --- */
    XPico_miner          Pico_miner_inst;
    XPico_miner_Config  *Pico_miner_cfg_ptr;
    int hw_status_init;
    int i;

    /* =========================================================================
     * Bitcoin Block 170 header (real-world test vector)
     *
     * Block 170 is the first block with a non-coinbase transaction
     * (Satoshi -> Hal Finney, 10 BTC).
     *
     * Header (80 bytes, serialized little-endian hex):
     *   01000000
     *   55bd840a78798ad0da853f68974f3d183e2bd1db6a842c1feecf222a00000000
     *   ff104ccb05421ab93e63f8c3ce5c2c2e9dbb37de2764b3a3175c8166562cac7d
     *   51b96a49
     *   ffff001d
     *   283e9e70
     *
     * Known winning nonce (LE): 0x283e9e70  -> (BE): 0x709e3e28
     * Block hash (display order):
     *   00000000d1145790a8694403d4063f323d499e655c83426834d4ce2f8dd4a2ee
     * ========================================================================= */

    unsigned int header_le[20] = {
        0x00000001u,  /* version */
        /* prev_hash (8 words, LE): */
        0x0a84bd55u, 0xd08a7978u, 0x683f85dau, 0x183d4f97u,
        0xdbd12b3eu, 0x1f2c846au, 0x2a22cfeeu, 0x00000000u,
        /* merkle_root (8 words, LE): */
        0xcb4c10ffu, 0xb91a4205u, 0xc3f8633eu, 0x2e2c5cceu,
        0xde37bb9du, 0xa3b36427u, 0x66815c17u, 0x7dac2c56u,
        /* timestamp, bits, nonce (LE): */
        0x496ab951u,
        0x1d00ffffu,
        0x709e3e28u
    };

    /* Byte-swap to big-endian for SHA-256 processing */
    unsigned int header_be[20];
    for (i = 0; i < 20; i++)
        header_be[i] = bswap32(header_le[i]);

    /* --- Compute midstate on ARM: SHA-256 compress chunk 1 (words 0-15) --- */
    unsigned int chunk1[16];
    for (i = 0; i < 16; i++) chunk1[i] = header_be[i];

    unsigned int midstate[MIDSTATE_WORDS];
    sha256_compress_sw(SHA256_H_INIT, chunk1, midstate);

    /* --- Extract chunk 2 tail: header words 16, 17, 18 (BE) --- */
    unsigned int chunk2_tail[CHUNK2_TAIL_WORDS] = {
        header_be[16], header_be[17], header_be[18]
    };

    /* --- Mining parameters --- */
    unsigned int known_nonce_be = header_be[19];  /* 0x709e3e28 */
    unsigned int nonce_start    = known_nonce_be - 16;
    unsigned int nonce_end      = known_nonce_be + 16;
    unsigned int target_hi      = 0x00000000u;  /* difficulty 1 */

    /* --- Result variables --- */
    unsigned int hw_nonce, hw_mining_status;
    unsigned int sw_nonce, sw_mining_status;

    /* =========================================================================
     * Platform initialization
     * ========================================================================= */
    Xil_ICacheEnable();
    Xil_DCacheEnable();

    printf("\r\n");
    printf("############################################################\r\n");
    printf("#                                                          #\r\n");
    printf("#      PICO MINER -- Bitcoin SHA-256 FPGA Accelerator      #\r\n");
    printf("#         ARM Driver (Zynq PS) + HLS IP (PL)               #\r\n");
    printf("#                                                          #\r\n");
    printf("############################################################\r\n");
    printf("\r\n");

    printf("[INFO] Test vector: Bitcoin Block 170\r\n");
    printf("[INFO] Known nonce (BE): 0x%08X\r\n", known_nonce_be);
    printf("[INFO] Nonce search range: [0x%08X, 0x%08X)\r\n",
           nonce_start, nonce_end);
    printf("[INFO] Target (hi word): 0x%08X\r\n", target_hi);
    printf("\r\n");

    printf("[ARM] Midstate: ");
    for (i = 0; i < 8; i++) printf("%08x ", midstate[i]);
    printf("\r\n");
    printf("[ARM] Chunk2 tail: [%08x, %08x, %08x]\r\n",
           chunk2_tail[0], chunk2_tail[1], chunk2_tail[2]);
    printf("\r\n");

    /* =========================================================================
     * Step 1: Initialize HLS IP
     * ========================================================================= */
    printf("[INIT] Looking up Pico Miner IP configuration...\r\n");
    Pico_miner_cfg_ptr = XPico_miner_LookupConfig(XPAR_PICO_MINER_0_DEVICE_ID);

    if (!Pico_miner_cfg_ptr) {
        printf("[ERROR] Could not find Pico Miner IP configuration!\r\n");
        printf("[ERROR] Check that the IP is instantiated in the block design.\r\n");
        Xil_DCacheDisable();
        Xil_ICacheDisable();
        return XST_FAILURE;
    }

    hw_status_init = XPico_miner_CfgInitialize(&Pico_miner_inst,
                                                 Pico_miner_cfg_ptr);
    if (hw_status_init != XST_SUCCESS) {
        printf("[ERROR] Failed to initialize Pico Miner IP (status=%d)\r\n",
               hw_status_init);
        Xil_DCacheDisable();
        Xil_ICacheDisable();
        return XST_FAILURE;
    }
    printf("[INIT] Pico Miner IP initialized successfully.\r\n\r\n");

    /* =========================================================================
     * Step 2: Write mining parameters to HLS IP via AXI-Lite
     *
     * Vivado HLS 2019.1 maps array arguments as individual scalar registers:
     *   midstate[8]     -> Set_midstate_0 .. Set_midstate_7
     *   chunk2_tail[3]  -> Set_chunk2_tail_0 .. Set_chunk2_tail_2
     * ========================================================================= */
    printf("[CONFIG] Writing midstate to FPGA...\r\n");
    XPico_miner_Set_midstate_0(&Pico_miner_inst, midstate[0]);
    XPico_miner_Set_midstate_1(&Pico_miner_inst, midstate[1]);
    XPico_miner_Set_midstate_2(&Pico_miner_inst, midstate[2]);
    XPico_miner_Set_midstate_3(&Pico_miner_inst, midstate[3]);
    XPico_miner_Set_midstate_4(&Pico_miner_inst, midstate[4]);
    XPico_miner_Set_midstate_5(&Pico_miner_inst, midstate[5]);
    XPico_miner_Set_midstate_6(&Pico_miner_inst, midstate[6]);
    XPico_miner_Set_midstate_7(&Pico_miner_inst, midstate[7]);

    printf("[CONFIG] Writing chunk2 tail to FPGA...\r\n");
    XPico_miner_Set_chunk2_tail_0(&Pico_miner_inst, chunk2_tail[0]);
    XPico_miner_Set_chunk2_tail_1(&Pico_miner_inst, chunk2_tail[1]);
    XPico_miner_Set_chunk2_tail_2(&Pico_miner_inst, chunk2_tail[2]);

    printf("[CONFIG] Writing scalar parameters...\r\n");
    XPico_miner_Set_nonce_start(&Pico_miner_inst, nonce_start);
    XPico_miner_Set_nonce_end(&Pico_miner_inst, nonce_end);
    XPico_miner_Set_target_hi(&Pico_miner_inst, target_hi);
    printf("\r\n");

    /* =========================================================================
     * Step 3: Start hardware mining and wait for completion
     * ========================================================================= */
    printf("[MINING] Starting hardware miner...\r\n");
    XPico_miner_Start(&Pico_miner_inst);

    /* Poll ap_done flag */
    printf("[MINING] Waiting for completion (polling ap_done)...\r\n");
    while (!XPico_miner_IsDone(&Pico_miner_inst)) {
        /* Busy wait -- in a real system you could use interrupts */
    }
    printf("[MINING] Hardware miner finished!\r\n\r\n");

    /* =========================================================================
     * Step 4: Read results from HLS IP
     * ========================================================================= */
    hw_nonce         = XPico_miner_Get_found_nonce(&Pico_miner_inst);
    hw_mining_status = XPico_miner_Get_status(&Pico_miner_inst);

    printf("[HW RESULT] Status: %s\r\n",
           (hw_mining_status == MINING_FOUND) ? "FOUND" : "NOT FOUND");
    if (hw_mining_status == MINING_FOUND) {
        printf("[HW RESULT] Winning nonce (BE): 0x%08X\r\n", hw_nonce);
        printf("[HW RESULT] Winning nonce (LE): 0x%08X\r\n", bswap32(hw_nonce));
    }
    printf("\r\n");

    /* =========================================================================
     * Step 5: Run software golden model and compare
     * ========================================================================= */
    printf("[SW] Running software reference miner for verification...\r\n");
    pico_miner_sw(midstate, chunk2_tail, nonce_start, nonce_end,
                  target_hi, &sw_nonce, &sw_mining_status);

    if (sw_mining_status == MINING_FOUND) {
        printf("[SW RESULT] Winning nonce (BE): 0x%08X\r\n", sw_nonce);
    } else {
        printf("[SW RESULT] Not found in range.\r\n");
    }
    printf("\r\n");

    /* =========================================================================
     * Step 6: Compare SW vs HW results
     * ========================================================================= */
    printf("============================================================\r\n");
    printf("           SW vs HW Comparison\r\n");
    printf("============================================================\r\n");
    printf("  Status:  SW=%u  HW=%u  %s\r\n",
           sw_mining_status, hw_mining_status,
           (sw_mining_status == hw_mining_status) ? "[OK]" : "[MISMATCH]");
    printf("  Nonce:   SW=0x%08X  HW=0x%08X  %s\r\n",
           sw_nonce, hw_nonce,
           (sw_nonce == hw_nonce) ? "[OK]" : "[MISMATCH]");
    printf("============================================================\r\n");

    if (sw_mining_status == hw_mining_status && sw_nonce == hw_nonce) {
        printf("\r\n  >>> ALL RESULTS MATCH -- VERIFICATION PASSED <<<\r\n");
    } else {
        printf("\r\n  >>> MISMATCH DETECTED -- VERIFICATION FAILED <<<\r\n");
    }

    /* =========================================================================
     * Additional: Verify against known Block 170 nonce
     * ========================================================================= */
    printf("\r\n");
    printf("============================================================\r\n");
    printf("           Block 170 Nonce Check\r\n");
    printf("============================================================\r\n");
    if (hw_mining_status == MINING_FOUND && hw_nonce == known_nonce_be) {
        printf("  HW nonce matches Bitcoin Block 170 nonce: [OK]\r\n");
    } else if (hw_mining_status == MINING_FOUND) {
        printf("  HW found nonce 0x%08X (differs from known 0x%08X)\r\n",
               hw_nonce, known_nonce_be);
        printf("  (May be another valid nonce in the search range)\r\n");
    } else {
        printf("  HW did not find a valid nonce: [FAIL]\r\n");
    }
    printf("============================================================\r\n");
    printf("\r\n");

    /* =========================================================================
     * Cleanup
     * ========================================================================= */
    Xil_DCacheDisable();
    Xil_ICacheDisable();
    return 0;
}
