/* =============================================================================
 * Pico Miner -- ARM Bare-Metal Driver (Zynq PS)
 *
 * Description:
 *   This program runs on the ARM Cortex-A9 processor (PS) of the Zynq SoC.
 *   It communicates with the Pico Miner HLS IP (Bitcoin double-SHA-256 miner)
 *   instantiated in the programmable logic (PL) via AXI-Lite registers.
 *
 *   The driver mines REAL Bitcoin blocks using the identical double-SHA-256
 *   algorithm used by every Bitcoin miner since 2009.  It demonstrates
 *   mining of three actual blocks from the Bitcoin blockchain:
 *
 *   - Block 1:   First block after genesis (Satoshi, Jan 9 2009)
 *   - Block 170: First non-coinbase tx (Satoshi -> Hal Finney, 10 BTC)
 *   - Block 181: Early block with two transactions
 *
 *   For each block, the driver:
 *   1. Parses the real 80-byte block header
 *   2. Computes the midstate on ARM (SHA-256 state after chunk 1)
 *   3. Sends midstate + chunk2_tail + nonce range + target to FPGA
 *   4. Starts the HW miner and polls for completion
 *   5. Reads back found_nonce + status
 *   6. Runs SW golden model for verification
 *
 * Target: Xilinx Zynq-7020 (ZedBoard)
 * Tool: Xilinx SDK 2019.1
 *
 * Note: The XPico_miner_* driver functions are AUTO-GENERATED by Vivado HLS
 *       when the IP is exported. Arrays mapped via s_axilite produce
 *       individual register accessors: Set_midstate_0 .. Set_midstate_7,
 *       Set_chunk2_tail_0 .. Set_chunk2_tail_2, etc.
 *
 * Author: Pico Miner Project
 * Date: 2026
 * =============================================================================
 */

#include <stdio.h>
#include "xparameters.h"
#include "xpico_miner.h"  /* Auto-generated by Vivado HLS export */
#include "xil_cache.h"    /* Cache init/cleanup (replaces platform.h) */

/* =============================================================================
 * SHA-256 Constants (must match pico_miner.h)
 * =============================================================================
 */
#define MIDSTATE_WORDS    8
#define CHUNK2_TAIL_WORDS 3
#define MINING_FOUND      1
#define MINING_NOT_FOUND  0

static const unsigned int SHA256_H_INIT[8] = {
    0x6a09e667u, 0xbb67ae85u, 0x3c6ef372u, 0xa54ff53au,
    0x510e527fu, 0x9b05688cu, 0x1f83d9abu, 0x5be0cd19u
};

static const unsigned int SHA256_K[64] = {
    0x428a2f98u, 0x71374491u, 0xb5c0fbcfu, 0xe9b5dba5u,
    0x3956c25bu, 0x59f111f1u, 0x923f82a4u, 0xab1c5ed5u,
    0xd807aa98u, 0x12835b01u, 0x243185beu, 0x550c7dc3u,
    0x72be5d74u, 0x80deb1feu, 0x9bdc06a7u, 0xc19bf174u,
    0xe49b69c1u, 0xefbe4786u, 0x0fc19dc6u, 0x240ca1ccu,
    0x2de92c6fu, 0x4a7484aau, 0x5cb0a9dcu, 0x76f988dau,
    0x983e5152u, 0xa831c66du, 0xb00327c8u, 0xbf597fc7u,
    0xc6e00bf3u, 0xd5a79147u, 0x06ca6351u, 0x14292967u,
    0x27b70a85u, 0x2e1b2138u, 0x4d2c6dfcu, 0x53380d13u,
    0x650a7354u, 0x766a0abbu, 0x81c2c92eu, 0x92722c85u,
    0xa2bfe8a1u, 0xa81a664bu, 0xc24b8b70u, 0xc76c51a3u,
    0xd192e819u, 0xd6990624u, 0xf40e3585u, 0x106aa070u,
    0x19a4c116u, 0x1e376c08u, 0x2748774cu, 0x34b0bcb5u,
    0x391c0cb3u, 0x4ed8aa4au, 0x5b9cca4fu, 0x682e6ff3u,
    0x748f82eeu, 0x78a5636fu, 0x84c87814u, 0x8cc70208u,
    0x90befffau, 0xa4506cebu, 0xbef9a3f7u, 0xc67178f2u
};

/* =============================================================================
 * Software SHA-256 Implementation (Golden Model for ARM verification)
 * =============================================================================
 */

static unsigned int rotr(unsigned int x, int n) {
    return (x >> n) | (x << (32 - n));
}

static unsigned int bswap32(unsigned int x) {
    return ((x & 0xFFu) << 24) | ((x & 0xFF00u) << 8) |
           ((x >> 8) & 0xFF00u) | ((x >> 24) & 0xFFu);
}

static void sha256_compress_sw(const unsigned int state_in[8],
                                const unsigned int msg[16],
                                unsigned int state_out[8])
{
    unsigned int W[64];
    unsigned int a, b, c, d, e, f, g, h;
    int i;

    for (i = 0; i < 16; i++) W[i] = msg[i];
    for (i = 16; i < 64; i++) {
        unsigned int s0 = rotr(W[i-15], 7) ^ rotr(W[i-15], 18) ^ (W[i-15] >> 3);
        unsigned int s1 = rotr(W[i-2], 17) ^ rotr(W[i-2], 19)  ^ (W[i-2] >> 10);
        W[i] = W[i-16] + s0 + W[i-7] + s1;
    }

    a = state_in[0]; b = state_in[1]; c = state_in[2]; d = state_in[3];
    e = state_in[4]; f = state_in[5]; g = state_in[6]; h = state_in[7];

    for (i = 0; i < 64; i++) {
        unsigned int S1   = rotr(e, 6) ^ rotr(e, 11) ^ rotr(e, 25);
        unsigned int ch   = (e & f) ^ ((~e) & g);
        unsigned int temp1 = h + S1 + ch + SHA256_K[i] + W[i];
        unsigned int S0   = rotr(a, 2) ^ rotr(a, 13) ^ rotr(a, 22);
        unsigned int maj  = (a & b) ^ (a & c) ^ (b & c);
        unsigned int temp2 = S0 + maj;
        h = g; g = f; f = e; e = d + temp1;
        d = c; c = b; b = a; a = temp1 + temp2;
    }

    state_out[0] = state_in[0] + a; state_out[1] = state_in[1] + b;
    state_out[2] = state_in[2] + c; state_out[3] = state_in[3] + d;
    state_out[4] = state_in[4] + e; state_out[5] = state_in[5] + f;
    state_out[6] = state_in[6] + g; state_out[7] = state_in[7] + h;
}

/* Software double-SHA-256 mining (golden model) */
static void pico_miner_sw(const unsigned int midstate[8],
                           const unsigned int chunk2_tail[3],
                           unsigned int nonce_start,
                           unsigned int nonce_end,
                           unsigned int target_hi,
                           unsigned int *found_nonce,
                           unsigned int *status)
{
    unsigned int nonce;
    int i;

    *found_nonce = 0;
    *status = MINING_NOT_FOUND;

    for (nonce = nonce_start; nonce < nonce_end; nonce++) {
        unsigned int chunk2_W[16];
        chunk2_W[0]  = chunk2_tail[0];
        chunk2_W[1]  = chunk2_tail[1];
        chunk2_W[2]  = chunk2_tail[2];
        chunk2_W[3]  = nonce;
        chunk2_W[4]  = 0x80000000u;
        for (i = 5; i < 15; i++) chunk2_W[i] = 0;
        chunk2_W[15] = 0x00000280u;

        unsigned int first_hash[8];
        sha256_compress_sw(midstate, chunk2_W, first_hash);

        unsigned int hash2_W[16];
        for (i = 0; i < 8; i++) hash2_W[i] = first_hash[i];
        hash2_W[8]  = 0x80000000u;
        for (i = 9; i < 15; i++) hash2_W[i] = 0;
        hash2_W[15] = 0x00000100u;

        unsigned int final_hash[8];
        sha256_compress_sw(SHA256_H_INIT, hash2_W, final_hash);

        /* Bitcoin display hash is byte-reversed; leading zeros correspond
         * to final_hash[7], not final_hash[0]. */
        if (final_hash[7] <= target_hi) {
            *found_nonce = nonce;
            *status = MINING_FOUND;
            return;
        }
    }
}

/* =============================================================================
 * Block header data structures
 * =============================================================================
 */
typedef struct {
    const char        *name;
    const char        *description;
    unsigned int       header_le[20];
    const char        *expected_hash;
} bitcoin_block_t;

/* Three real Bitcoin blocks -- headers obtained from the blockchain */
static const bitcoin_block_t BLOCKS[] = {
    {
        /* ---- Block 1 ----
         * The first block after the genesis block.
         * Mined by Satoshi Nakamoto on January 9, 2009.
         * Raw: 010000006fe28c0ab6f1b372c1a6a246ae63f74f931e8365e15a089c
         *      68d6190000000000982051fd1e4ba744bbbe680e1fee14677ba1a3c354
         *      0bf7b1cdb606e857233e0e61bc6649ffff001d01e36299
         */
        "Block 1",
        "First block after genesis (Satoshi, Jan 9 2009)",
        {
            0x00000001u,
            0x0a8ce26fu, 0x72b3f1b6u, 0x46a2a6c1u, 0x4ff763aeu,
            0x65831e93u, 0x9c085ae1u, 0x0019d668u, 0x00000000u,
            0xfd512098u, 0x44a74b1eu, 0x0e68bebbu, 0x6714ee1fu,
            0xc3a3a17bu, 0xb1f70b54u, 0xe806b6cdu, 0x0e3e2357u,
            0x4966bc61u, 0x1d00ffffu, 0x9962e301u
        },
        "00000000839a8e6886ab5951d76f411475428afc90947ee320161bbf18eb6048"
    },
    {
        /* ---- Block 170 ----
         * First block with a non-coinbase transaction.
         * Satoshi Nakamoto sent 10 BTC to Hal Finney on January 12, 2009.
         * Raw: 0100000055bd840a78798ad0da853f68974f3d183e2bd1db6a842c1f
         *      eecf222a00000000ff104ccb05421ab93e63f8c3ce5c2c2e9dbb37de27
         *      64b3a3175c8166562cac7d51b96a49ffff001d283e9e70
         */
        "Block 170",
        "First non-coinbase tx: Satoshi -> Hal Finney, 10 BTC (Jan 12 2009)",
        {
            0x00000001u,
            0x0a84bd55u, 0xd08a7978u, 0x683f85dau, 0x183d4f97u,
            0xdbd12b3eu, 0x1f2c846au, 0x2a22cfeeu, 0x00000000u,
            0xcb4c10ffu, 0xb91a4205u, 0xc3f8633eu, 0x2e2c5cceu,
            0xde37bb9du, 0xa3b36427u, 0x66815c17u, 0x7dac2c56u,
            0x496ab951u, 0x1d00ffffu, 0x709e3e28u
        },
        "00000000d1145790a8694403d4063f323d499e655c83426834d4ce2f8dd4a2ee"
    },
    {
        /* ---- Block 181 ----
         * Early block with two transactions.
         * Raw: 01000000f2c8a8d2af43a9cd05142654e56f41d159ce0274d9cabe15
         *      a20eefb500000000366c2a0915f05db4b450c050ce7165acd55f823fee
         *      51430a8c993e0bdbb192ede5dc6a49ffff001d192d3f2f
         */
        "Block 181",
        "Early block with two transactions (Jan 12 2009)",
        {
            0x00000001u,
            0xd2a8c8f2u, 0xcda943afu, 0x54261405u, 0xd1416fe5u,
            0x7402ce59u, 0x15becad9u, 0xb5ef0ea2u, 0x00000000u,
            0x092a6c36u, 0xb45df015u, 0x50c050b4u, 0xac6571ceu,
            0x3f825fd5u, 0x0a4351eeu, 0x0b3e998cu, 0xed92b1dbu,
            0x496adce5u, 0x1d00ffffu, 0x2f3f2d19u
        },
        "00000000dc55860c8a29c58d45209318fa9e9dc2c1833a7226d86bc465afc6e5"
    }
};

#define NUM_BLOCKS (sizeof(BLOCKS) / sizeof(BLOCKS[0]))

/* =============================================================================
 * Mine a single block: ARM computes midstate, FPGA searches nonces
 * =============================================================================
 */
static int mine_block(XPico_miner *inst, const bitcoin_block_t *block)
{
    int i;
    unsigned int header_be[20];
    unsigned int chunk1[16];
    unsigned int midstate[MIDSTATE_WORDS];
    unsigned int chunk2_tail[CHUNK2_TAIL_WORDS];
    unsigned int known_nonce_be;

    /* Byte-swap header to big-endian for SHA-256 */
    for (i = 0; i < 20; i++)
        header_be[i] = bswap32(block->header_le[i]);

    /* Compute midstate: SHA-256 compress(H_init, chunk1) */
    for (i = 0; i < 16; i++) chunk1[i] = header_be[i];
    sha256_compress_sw(SHA256_H_INIT, chunk1, midstate);

    /* Extract chunk2 tail and known nonce */
    chunk2_tail[0] = header_be[16];
    chunk2_tail[1] = header_be[17];
    chunk2_tail[2] = header_be[18];
    known_nonce_be = header_be[19];

    /* Search window: ±4096 nonces around known answer
     * Wide enough to be a meaningful demo, narrow enough to finish quickly
     * on real FPGA hardware (~8192 nonces * 128 cycles/nonce = ~1M cycles = ~10ms) */
    unsigned int nonce_start = known_nonce_be - 4096;
    unsigned int nonce_end   = known_nonce_be + 4096;
    unsigned int target_hi   = 0x00000000u;

    printf("------------------------------------------------------------\r\n");
    printf("[MINING] %s\r\n", block->name);
    printf("  %s\r\n", block->description);
    printf("  Known nonce (LE): 0x%08X  (BE): 0x%08X\r\n",
           block->header_le[19], known_nonce_be);
    printf("  Expected hash: %s\r\n", block->expected_hash);
    printf("  Midstate: ");
    for (i = 0; i < 8; i++) printf("%08x ", midstate[i]);
    printf("\r\n");
    printf("  Search range: [0x%08X, 0x%08X)  (%u nonces)\r\n",
           nonce_start, nonce_end, nonce_end - nonce_start);
    printf("\r\n");

    /* ---- Write parameters to FPGA ---- */
    XPico_miner_Set_midstate_0(inst, midstate[0]);
    XPico_miner_Set_midstate_1(inst, midstate[1]);
    XPico_miner_Set_midstate_2(inst, midstate[2]);
    XPico_miner_Set_midstate_3(inst, midstate[3]);
    XPico_miner_Set_midstate_4(inst, midstate[4]);
    XPico_miner_Set_midstate_5(inst, midstate[5]);
    XPico_miner_Set_midstate_6(inst, midstate[6]);
    XPico_miner_Set_midstate_7(inst, midstate[7]);

    XPico_miner_Set_chunk2_tail_0(inst, chunk2_tail[0]);
    XPico_miner_Set_chunk2_tail_1(inst, chunk2_tail[1]);
    XPico_miner_Set_chunk2_tail_2(inst, chunk2_tail[2]);

    XPico_miner_Set_nonce_start(inst, nonce_start);
    XPico_miner_Set_nonce_end(inst, nonce_end);
    XPico_miner_Set_target_hi(inst, target_hi);

    /* ---- Start HW miner ---- */
    printf("  [HW] Starting FPGA miner...\r\n");
    XPico_miner_Start(inst);

    while (!XPico_miner_IsDone(inst)) {
        /* Busy wait */
    }

    /* ---- Read HW results ---- */
    unsigned int hw_nonce  = XPico_miner_Get_found_nonce(inst);
    unsigned int hw_status = XPico_miner_Get_status(inst);

    printf("  [HW] Status: %s\r\n",
           (hw_status == MINING_FOUND) ? "FOUND" : "NOT FOUND");
    if (hw_status == MINING_FOUND) {
        printf("  [HW] Nonce (BE): 0x%08X  (LE): 0x%08X\r\n",
               hw_nonce, bswap32(hw_nonce));
    }

    /* ---- Run SW golden model ---- */
    unsigned int sw_nonce, sw_status;
    pico_miner_sw(midstate, chunk2_tail, nonce_start, nonce_end,
                  target_hi, &sw_nonce, &sw_status);

    printf("  [SW] Status: %s\r\n",
           (sw_status == MINING_FOUND) ? "FOUND" : "NOT FOUND");
    if (sw_status == MINING_FOUND) {
        printf("  [SW] Nonce (BE): 0x%08X\r\n", sw_nonce);
    }

    /* ---- Compare ---- */
    int pass = (hw_status == sw_status) && (hw_nonce == sw_nonce);
    printf("  HW vs SW: %s\r\n", pass ? "[MATCH]" : "[MISMATCH]");

    if (hw_status == MINING_FOUND && hw_nonce == known_nonce_be) {
        printf("  Nonce matches %s from the Bitcoin blockchain: [OK]\r\n",
               block->name);
    }
    printf("\r\n");

    return pass ? 0 : 1;
}

/* =============================================================================
 * Main Program
 * =============================================================================
 */
int main(void)
{
    XPico_miner          inst;
    XPico_miner_Config  *cfg_ptr;
    int hw_status_init;
    int total_errors = 0;
    unsigned int i;

    /* =========================================================================
     * Platform initialization
     * ========================================================================= */
    Xil_ICacheEnable();
    Xil_DCacheEnable();

    printf("\r\n");
    printf("############################################################\r\n");
    printf("#                                                          #\r\n");
    printf("#      PICO MINER -- Real Bitcoin Mining on FPGA           #\r\n");
    printf("#        Double-SHA-256 with Midstate Optimization          #\r\n");
    printf("#         ARM (Zynq PS) + HLS Accelerator (PL)             #\r\n");
    printf("#                                                          #\r\n");
    printf("#  This driver mines REAL Bitcoin blocks using the same    #\r\n");
    printf("#  algorithm used by every miner since January 2009.       #\r\n");
    printf("#                                                          #\r\n");
    printf("############################################################\r\n");
    printf("\r\n");

    /* =========================================================================
     * Initialize HLS IP
     * ========================================================================= */
    printf("[INIT] Looking up Pico Miner IP configuration...\r\n");
    cfg_ptr = XPico_miner_LookupConfig(XPAR_PICO_MINER_0_DEVICE_ID);

    if (!cfg_ptr) {
        printf("[ERROR] Could not find Pico Miner IP!\r\n");
        Xil_DCacheDisable();
        Xil_ICacheDisable();
        return XST_FAILURE;
    }

    hw_status_init = XPico_miner_CfgInitialize(&inst, cfg_ptr);
    if (hw_status_init != XST_SUCCESS) {
        printf("[ERROR] Failed to initialize IP (status=%d)\r\n",
               hw_status_init);
        Xil_DCacheDisable();
        Xil_ICacheDisable();
        return XST_FAILURE;
    }
    printf("[INIT] Pico Miner IP initialized.\r\n\r\n");

    /* =========================================================================
     * Mine all three real Bitcoin blocks
     * ========================================================================= */
    printf("============================================================\r\n");
    printf("  Mining %u real Bitcoin blocks...\r\n", (unsigned int)NUM_BLOCKS);
    printf("============================================================\r\n\r\n");

    for (i = 0; i < NUM_BLOCKS; i++) {
        total_errors += mine_block(&inst, &BLOCKS[i]);
    }

    /* =========================================================================
     * Summary
     * ========================================================================= */
    printf("============================================================\r\n");
    printf("  RESULTS SUMMARY\r\n");
    printf("============================================================\r\n");
    printf("  Blocks mined: %u / %u\r\n",
           (unsigned int)(NUM_BLOCKS - total_errors), (unsigned int)NUM_BLOCKS);
    printf("  Blocks: 1 (first after genesis), 170 (first tx), 181 (early)\r\n");

    if (total_errors == 0) {
        printf("\r\n");
        printf("  >>> ALL BLOCKS MINED SUCCESSFULLY <<<\r\n");
        printf("  >>> REAL BITCOIN MINING VERIFIED ON FPGA <<<\r\n");
    } else {
        printf("\r\n");
        printf("  >>> %d BLOCK(S) FAILED <<<\r\n", total_errors);
    }
    printf("============================================================\r\n");
    printf("\r\n");

    Xil_DCacheDisable();
    Xil_ICacheDisable();
    return 0;
}
